server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: API_Gateway
  cloud:
    gateway:
      mvc:
        routes:
          routes:
            - id: User_Service
              uri: lb://User_Service
              predicates:
                - Path=/api/v1/user/**
            - id: Vehicle_Service
              uri: lb://Vehicle_Service
              predicates:
                - Path=/api/v1/vehicle/**
            - id: Ticket_Service
              uri: lb://Ticket_Service
              predicates:
                - Path=/api/v1/ticket/**
            - id: Payment_Service
              uri: lb://Payment_Service
              predicates:
                - Path=/api/v1/payment/**
